quarkus.rest.path=/api
quarkus.datasource.devservices.enabled=false

# Database setting
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/${DB_NAME:my_db}

# Enable CORS globally
quarkus.http.cors.enabled=true

# Allow frontend origin
quarkus.http.cors.origins=${FRONTEND_URL}

# Specify which methods are allowed
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Specify which headers are allowed (essential for Auth or JSON content)
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

# (Optional) How long the browser should cache the CORS preflight request
quarkus.http.cors.access-control-max-age=6H

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=public
quarkus.flyway.out-of-order=true
quarkus.flyway.baseline-on-migrate=true

quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
mp.orm.id-generation-strategy=identity

# Keycloak OIDC ? used by Quarkus to validate incoming JWT tokens
quarkus.oidc.auth-server-url=http://keycloak:${KEYCLOAK_PORT}/realms/drcp
quarkus.oidc.client-id=identity-service
quarkus.oidc.token.audience=identity-service
quarkus.oidc.application-type=service
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.keycloak.devservices.enabled=false

# Dev override ? localhost since Quarkus runs outside Docker
%dev.quarkus.oidc.auth-server-url=http://localhost:${KEYCLOAK_PORT}/realms/drcp

# Keycloak Admin Client ? used to manage users via Admin REST API
keycloak.admin.server-url=http://keycloak:${KEYCLOAK_PORT}
keycloak.admin.realm=drcp
keycloak.admin.client-id=identity-service
keycloak.admin.client-secret=${KEYCLOAK_CLIENT_SECRET}
keycloak.admin.target-realm=drcp

# Dev override
%dev.keycloak.admin.server-url=http://localhost:${KEYCLOAK_PORT}

# Run the application on a different port to avoid conflicts with Keycloak
%dev.quarkus.http.port=8900